REVIEWS = [
    "Kamarnya sangat bersih dan nyaman, betah banget menginap di sini.",
    "Pelayanan sangat ramah, stafnya sigap membantu segala keperluan.",
    "Lokasi strategis, dekat dengan pusat keramaian dan kuliner.",
    "Harga terjangkau dengan fasilitas yang sangat lengkap dan mewah.",
    "Sarapannya enak banget, banyak variasi menu yang menggugah selera.",
    "Pemandangan dari jendela kamar luar biasa indah, sangat menyejukkan.",
    "Proses check-in dan check-out sangat cepat, nggak pakai ribet.",
    "Sangat merekomendasikan hotel ini untuk liburan keluarga.",
    "Fasilitas kolam renang bersih dan terawat, anak-anak senang sekali.",
    "Interior kamar sangat modern dan estetik, cocok buat staycation.",
    "Suasana hotel sangat tenang, cocok buat yang mau healing.",
    "Tempat tidurnya empuk banget, bener-bener tidur nyenyak di sini.",
    "Akses Wi-fi kencang, sangat mendukung buat yang mau kerja remote.",
    "Kamar mandi bersih, air hangat berfungsi dengan sangat baik.",
    "Pelayanan housekeeping sangat rapi dan telaten membersihkan kamar.",
    "Parkir luas dan aman, petugas keamanannya juga sangat ramah.",
    "Dekat dengan transportasi umum, akses ke mana-mana jadi mudah.",
    "AC dingin dan tidak berisik, udara di kamar sangat segar.",
    "Disediakan perlengkapan mandi lengkap, aromanya juga sangat enak.",
    "Puas banget menginap di sini, pasti bakal balik lagi nanti.",
    "Hotel yang sangat ramah di kantong dengan kualitas bintang lima.",
    "Sangat suka dengan konsep desain interior lobi dan kamarnya.",
    "Layanan room service cepat, makanannya sampai dalam keadaan hangat.",
    "Banyak spot foto bagus di area hotel, instagramable banget.",
    "Keamanan terjaga 24 jam, menginap jadi terasa sangat tenang.",
    "Setiap sudut hotel sangat bersih, protokol kebersihan dijalankan.",
    "Staf resepsionis sangat membantu saat kami butuh informasi wisata.",
    "Ukuran kamar cukup luas untuk membawa banyak barang bawaan.",
    "Dekat dengan minimarket dan ATM, sangat terbantu saat darurat.",
    "Suara dari luar tidak terdengar masuk ke dalam kamar, kedap suara.",
    "Sangat puas dengan keramahan semua staf hotel, mantap!",
    "Tersedia air minum, kopi, dan teh gratis yang selalu diisi ulang.",
    "Pencahayaan kamar sangat pas, memberikan kesan yang hangat.",
    "Tidak ada bau rokok sama sekali di koridor maupun dalam kamar.",
    "Fasilitas gym-nya lengkap, alat-alatnya masih sangat baru.",
    "Area sekitar hotel sangat asri dengan banyak pepohonan hijau.",
    "Puas banget dengan layanan antar-jemput bandara yang disediakan.",
    "Hotel terbaik di kelasnya, tidak mengecewakan sama sekali.",
    "Sangat cocok untuk perjalanan bisnis maupun liburan singkat.",
    "Kamarnya harum dan segar saat pertama kali masuk, suka banget!",
    "Sarapan buffet-nya sangat lengkap, mulai dari menu lokal sampai western.",
    "Staf sangat memperhatikan detail kebutuhan pengunjung, luar biasa.",
    "Harga yang ditawarkan sangat kompetitif dibandingkan hotel sekitar.",
    "Tempatnya sangat privat, tidak bising sama sekali.",
    "Cocok buat yang cari ketenangan di tengah hiruk pikuk kota.",
    "Pelayanan kelas dunia dengan harga yang bersahabat.",
    "Sangat terbantu dengan layanan laundry yang cepat dan rapi.",
    "Pengalaman menginap yang sangat berkesan bagi saya dan pasangan.",
    "Semua fasilitas berfungsi 100%, dari TV sampai shower air hangat.",
    "Respon via chat atau telepon sangat cepat ditanggapi oleh staf.",
    "Sangat menghargai keramahan staf saat kami tiba di depan pintu.",
    "View malam hari dari rooftop hotel ini juara banget!",
    "Banyak pilihan bantal yang bisa dipilih sesuai kenyamanan.",
    "Lantai kamar selalu bersih, tidak ada debu sama sekali.",
    "Pelayanan sangat personal, merasa sangat dihargai sebagai tamu.",
    "Area restorannya sangat nyaman untuk bersantai sore hari.",
    "Sangat puas dengan kualitas sprei dan handuk yang disediakan.",
    "Setiap permintaan khusus kami dikabulkan dengan sangat baik.",
    "Proses reservasi sangat mudah dan konfirmasinya instan.",
    "Terima kasih atas pengalaman menginap yang luar biasa ini!"
]
