REVIEWS = [
    "Barang sangat bagus, pengiriman cepat sekali!",
    "Kualitas produk jempolan, sangat memuaskan.",
    "Layanan pelanggan sangat ramah dan membantu.",
    "Sangat merekomendasikan toko ini, respon sangat cepat.",
    "Barang sampai dengan selamat, packing rapi banget.",
    "Harga terjangkau tapi kualitas mewah.",
    "Bintang lima buat layanan dan produknya!",
    "Produk original, jangan ragu belanja di sini.",
    "Mantap jiwa, produk sesuai deskripsi.",
    "Terima kasih, pesanan sudah sampai sesuai jadwal.",
    "Kualitas oke punya, seller responsive.",
    "Packing sangat aman, barang mulus tanpa lecet.",
    "Kecepatan pengiriman luar biasa, terima kasih!",
    "Produk sangat membantu, kualitas tidak diragukan.",
    "Langganan di sini, selalu puas dengan pelayanannya.",
    "Puas banget belanja di sini, sukses terus ya!",
    "Barang real pict, kualitas sangat premium.",
    "Fast respon, pengiriman secepat kilat.",
    "Pelayanan juara, barang berkualitas tinggi.",
    "Sangat puas dengan barangnya, original 100%.",
    "Produknya bagus sekali, cocok buat harian.",
    "Seller sangat terpercaya, barang cepat sampai.",
    "Kemasan sangat rapi dan terjaga keamanannya.",
    "Barang bagus, sesuai ekspektasi, terima kasih.",
    "Recommended banget buat yang mau beli produk ini.",
    "Kualitas melebihi harga, sangat hemat.",
    "Pengiriman rapi, barang berfungsi dengan baik.",
    "Luar biasa cepat prosesnya, mantap seller!",
    "Barang berkualitas, packing tebal, aman!",
    "Top banget, barang sesuai gambar, pengiriman gesit.",
    "Produk sangat memuaskan, kualitas istimewa.",
    "Pengalaman belanja yang menyenangkan, terpercaya.",
    "Barang sudah diterima dengan kondisi sangat baik.",
    "Sangat senang dengan kualitas produknya, mantap!",
    "Respon penjual sangat baik, pengiriman juga cepat.",
    "Kualitas barang oke, original, dan murah.",
    "Toko terpercaya, pelayanan ramah, barang sip!",
    "Packaging luar biasa aman, produk sangat memuaskan.",
    "Sesuai deskripsi, respon cepat, pengiriman mantap.",
    "Puas sekali belanja di toko ini, recommended!",
    "Barang mantap, kualitas oke, seller ramah.",
    "Pengiriman super cepat, barang packing aman.",
    "Produk asli, sangat memuaskan, sukses terus.",
    "Pelayanan cepat dan ramah, barang berkualitas.",
    "Kualitas top markotop, jangan ragu beli di sini.",
    "Barang sudah sampai, kualitas sangat baik sekali.",
    "Harga bersahabat dengan kualitas ningrat.",
    "Toko langganan, selalu memuaskan kualitasnya.",
    "Respon luar biasa cepat, barang sampai selamat.",
    "Terbaik pelayanannya, produk berkualitas tinggi.",
    "Sangat puas, barang sesuai dengan foto profil.",
    "Pengiriman aman terkendali, produk jempolan.",
    "Kualitas produk mantap, packingnya juga istimewa.",
    "Sangat recommend, jangan pikir dua kali beli di sini!",
    "Produk bagus, seller ramah, pengiriman ekspres.",
    "Kualitas jempolan, harga terjangkau, seller top.",
    "Puas banget, packing rapi, barang original.",
    "Sesuai pesanan, kualitas mantap, pengiriman cepat.",
    "Layanan sangat memuaskan, barang real pict.",
    "Penjual ramah, barang berkualitas, sukses selalu!"
]
